### ISSUE TITLE
Saving Analysis for first time breaks line to dataset

### ISSUE THREAD

**Issue by peterdougstuart** [peterdougstuart/PCWG#170] opened 2016-10-16 21:13 UTC
Steps to recreate:
1) Create a new analysis
2) Add dataset
3) Save analysis => analysis doesn't properly save path to dataset

**Comment by lcameron05** [comment] 2016-11-04 18:03
In [pcwg/gui/analysis.py](https://github.com/peterdougstuart/PCWG/blob/master/pcwg/gui/analysis.py), the `add_datasets` method of `AnalysisConfigurationDialog` initialises the dataset grid box with `self.config.datasets.clone()`. `self.config.datasets` is an instance of `PathManager` from [pcwg/configuration/path_manager.py](https://github.com/peterdougstuart/PCWG/blob/master/pcwg/configuration/path_manager.py). As the `clone()` method is used, the base_folder at the time of creation is `None` if analysis is created from new and is never updated.

**Comment by lcameron05** [comment] 2016-11-07 11:36
My commit above fixes this issue. Setting the base of the `AnalysisConfigurationDialog.dataset_grid_box.datasets_file_manager` using the appropriate path before analysis config object is updated means changes to the analysis xml path are reflected in the dataset xml paths when the config is written.

There was a related issue that is also fixed by this change; editing the directory the analysis config xml was saved in would not result in the relative path to the dataset config(s) being updated in the analysis xml config. The cause was the same as the original issue.

**Closed** 2016-11-07 11:36 UTC
